apiVersion: v1
kind: Service
metadata:
  name: all-validators # +operator-builder:field:parent=metadata.name,type=string,replace="name"
  namespace: default # +operator-builder:field:parent=metadata.name,type=string
  labels:
    scope: all-validators
spec:
  ports:
    - port: 42069
      name: consensus
    - port: 50832
      name: rpc
    - port: 9000
      name: metrics
  clusterIP: None
  selector:
    purpose: validator
