apiVersion: nodes.pokt.network/v1alpha1
kind: PocketValidator
metadata:
  name: v1-validator3
spec:
  collection:
    name: default
  pocketImage: "ghcr.io/pokt-network/pocket-v1:main-dev"
  privateKey:
    secretKeyRef:
      name: v1-validator3
      key: private_key
  postgres:
    user:
      secretKeyRef:
        name: pocket-postgres-postgresql
        key: username
    password:
      secretKeyRef:
        name: pocket-postgres-postgresql
        key: postgres-password
    host: pocket-postgres-postgresql
    port: "5432"
    database: postgres
    schema: validator3
---
apiVersion: v1
kind: Secret
metadata:
  name: v1-validator3
type: Opaque
stringData:
  private_key: "c7bd1bd027e76b31534c3f5226c8e3c3f2a034ba9fa11017b65191f7f9ef0d253e5e4bbed5f98721163bb84445072a9202d213f1e348c5e9e0e2ea83bbb7e3aa"
