apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocket-v1-cli-client
  namespace: default
  labels:
    app: v1-cli-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v1-cli-client
  template:
    metadata:
      labels:
        app: v1-cli-client
    spec:
      containers:
        - name: pocket
          image: ghcr.io/pokt-network/pocket-v1:main-dev
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]
          env:
            - name: CONFIG_PATH
              value: "/var/pocket/config/config.json"
            - name: GENESIS_PATH
              value: "/var/pocket/genesis/genesis.json"
            - name: POCKET_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: v1-validator1
                  key: private_key
            - name: POCKET_CONSENSUS_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: v1-validator1
                  key: private_key
            - name: POCKET_P2P_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: v1-validator1
                  key: private_key
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: LocalNetPassword
            - name: POSTGRES_HOST
              value: pocket-postgres-postgresql
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POCKET_PERSISTENCE_POSTGRES_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
            - name: POCKET_PERSISTENCE_NODE_SCHEMA
              value: validator1
          volumeMounts:
            - mountPath: /var/pocket/config
              name: config-volume
            - mountPath: /var/pocket/genesis
              name: genesis-volume
      volumes:
        - name: config-volume
          configMap:
            name: v1-validator1-config
            defaultMode: 420
        - name: genesis-volume
          configMap:
            name: default-genesis
            defaultMode: 420
